sudo: true

language: python
python:
  - "3.6"

cache: pip

before_install:
  - pip install -U coverage pytest pytest-cov codecov pytest-pylint
  - sudo apt-get update
  - sudo apt-get install sqlite3=3.24.0-1
  - sqlite3 -version

install:
  - pip install -e .
  - python -m spacy download en_core_web_sm

script:
  - pytest --cov=./

after_success:
  - codecov
