sudo: true
dist: xenial
language: python
python:
- '3.7'
cache: pip
before_install:
- pip install -U coverage pytest pytest-cov codecov pytest-pylint
- sqlite3 -version
install:
- pip install -e .
- python -m spacy download en_core_web_sm
script:
- pytest -m "not dbtest" --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: dblintio
  password:
    secure: OXhAnmrdcKZfI0asl5NK13Y+Xgm/UjCap44hJaEZIKox7+mZt6kzCgHsHoFQoZRMA9g6Ir9etyw38uiGu5h7RTqlVIWpJJXZPj9oHGJGGfv91VEi98ouYuBHB8fy39Bc+NBQDslb+G4q70z3KfeW7CXrRtPasvGwNbRshk+oTTpkrV/XD8QjI66sFgSBPPvMtXPQ3RpM3DRv4z261eivTSEVTqw933E7zZ9733fGDzqDrmf41bqUvP109VfnlkfPl1O/LGEG3DVRJIjFNKSjqlENFEeO2GGD6tpq3RPPIKCu/4jlzEKaq2FojbrnqPui2RjSotut8iKzecjk5vi1NpX486yUnY1mou0KDmrFFyD51UpXyTSTp/eBb5OvAJQ8HyY7oHxRW/EggqKFUVjtD5WB/PQ7/Jsf3N1U2Uo20EsrzxibZOnLPBvPCUDKdfl6zoBPMXo0hdXRIdsMa1HgBlquU1G0jUiks2mxDjD4wqB6KZFhscFsrLxFV1yoJ6vp85uXWQjv/gjCGN3RpBZdpyz9hAKFqfKUYCN+LTxaiTeMbldCJvwgYASXpzIiFFytypTyeGyuXOMmXe1TRWR/9+uLNE4JGH48yXNlS1CEFx9/SimN+JRJQwWaJHkyJh00YgKT9N7pjMlvxMjQTuH6/icpyCGi6SVgqKR7G+0EqIw=
  on:
    tags: true
    branch: master
    distributions: "sdist bdist_wheel"
    python: '3.7'
